# name: Commit-Release

# on:
#   push:
#     branches:
#       - 'feature/**' 

# jobs:
#   commit-release:
#     permissions:
#         contents: write
#     name: Semantic Release
#     runs-on: ubuntu-latest
#     # if: ${{ github.ref == 'refs/heads/main'}}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           registry-url: 'https://registry.npmjs.org'

#       - name: Install dependencies
#         run: npm install

#   publish-release:
#     permissions:
#         contents: write
#     name: Semantic Release
#     runs-on: ubuntu-latest
#     if: ${{ github.ref == 'refs/heads/main'}}
#     needs: [commit-release]

#     steps:
#       - name: Semantic Release Publish
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB }}
#         run: npx semantic-release
